"""Canonical HTTP paths shared by routers and generated contracts."""

API_PREFIX = "/api"
API_V1_PREFIX = "/v1"
BROWSER_SESSION_PREFIX = "/sessions"

BROWSER_SESSION_LOGIN_PATH = "/login"
BROWSER_SESSION_LOGOUT_PATH = "/logout"
BROWSER_SESSION_CSRF_PATH = "/csrf"

API_V1_BROWSER_SESSION_PREFIX = f"{API_PREFIX}{API_V1_PREFIX}{BROWSER_SESSION_PREFIX}"
API_V1_BROWSER_SESSION_LOGIN_PATH = (
    f"{API_V1_BROWSER_SESSION_PREFIX}{BROWSER_SESSION_LOGIN_PATH}"
)
API_V1_BROWSER_SESSION_LOGOUT_PATH = (
    f"{API_V1_BROWSER_SESSION_PREFIX}{BROWSER_SESSION_LOGOUT_PATH}"
)
API_V1_BROWSER_SESSION_CSRF_PATH = (
    f"{API_V1_BROWSER_SESSION_PREFIX}{BROWSER_SESSION_CSRF_PATH}"
)

OAUTH2_PREFIX = "/oauth2"
OAUTH2_AUTHORIZE_PATH = "/authorize"
OAUTH2_AUTHORIZE_DECISION_PATH = "/authorize/decision"
OAUTH2_TOKEN_PATH = "/token"  # noqa: S105
OAUTH2_REVOCATION_PATH = "/revoke"
OAUTH2_INTROSPECTION_PATH = "/introspect"
OAUTH2_DEVICE_AUTHORIZATION_PATH = "/device_authorization"
OAUTH2_USERINFO_PATH = "/userinfo"

OAUTH2_AUTHORIZE_ENDPOINT = f"{OAUTH2_PREFIX}{OAUTH2_AUTHORIZE_PATH}"
OAUTH2_AUTHORIZE_DECISION_ENDPOINT = f"{OAUTH2_PREFIX}{OAUTH2_AUTHORIZE_DECISION_PATH}"
OAUTH2_TOKEN_ENDPOINT = f"{OAUTH2_PREFIX}{OAUTH2_TOKEN_PATH}"
OAUTH2_REVOCATION_ENDPOINT = f"{OAUTH2_PREFIX}{OAUTH2_REVOCATION_PATH}"
OAUTH2_INTROSPECTION_ENDPOINT = f"{OAUTH2_PREFIX}{OAUTH2_INTROSPECTION_PATH}"
OAUTH2_DEVICE_AUTHORIZATION_ENDPOINT = (
    f"{OAUTH2_PREFIX}{OAUTH2_DEVICE_AUTHORIZATION_PATH}"
)
OAUTH2_USERINFO_ENDPOINT = f"{OAUTH2_PREFIX}{OAUTH2_USERINFO_PATH}"
