"""Multiprocess tests for Snowflake node allocation."""

from __future__ import annotations

from multiprocessing import get_context
from pathlib import Path
from typing import cast, TYPE_CHECKING

import pytest
from app.db.snowflake import (
    acquire_snowflake_node_lease,
    configure_snowflake_generator,
    generate_snowflake_id,
    SNOWFLAKE_MAX_NODE_ID,
    SNOWFLAKE_NODE_ID_SHIFT,
    unconfigure_snowflake_generator,
)


if TYPE_CHECKING:
    from multiprocessing.connection import Connection
    from multiprocessing.process import BaseProcess
    from multiprocessing.synchronize import Event


pytestmark = pytest.mark.integration
WORKER_COUNT = 4
IDS_PER_WORKER = 256
type WorkerResult = tuple[int, list[int]]


def _generate_ids_in_worker(
    lock_directory: str,
    connection: Connection,
    release_workers: Event,
) -> None:
    """Hold one node while reporting IDs generated by a child process."""
    lease = acquire_snowflake_node_lease(
        lock_directory=Path(lock_directory),
        requested_node_id=None,
    )
    try:
        configure_snowflake_generator(lease.node_id)
        generated_ids = [int(generate_snowflake_id()) for _ in range(IDS_PER_WORKER)]
        connection.send((lease.node_id, generated_ids))
        release_workers.wait(timeout=10)
    finally:
        unconfigure_snowflake_generator()
        lease.release()
        connection.close()


def test_workers_allocate_distinct_nodes_and_generate_unique_ids(
    tmp_path: Path,
) -> None:
    """Coordinate concurrent workers through their shared lock directory."""
    context = get_context("spawn")
    release_workers = context.Event()
    parent_connections: list[Connection] = []
    processes: list[BaseProcess] = []

    for _ in range(WORKER_COUNT):
        parent_connection, child_connection = context.Pipe(duplex=False)
        process = context.Process(
            target=_generate_ids_in_worker,
            args=(str(tmp_path), child_connection, release_workers),
        )
        parent_connections.append(parent_connection)
        processes.append(process)
        process.start()
        child_connection.close()

    try:
        results: list[WorkerResult] = []
        for connection in parent_connections:
            assert connection.poll(10), "Snowflake worker did not report startup"
            results.append(cast("WorkerResult", connection.recv()))
    finally:
        release_workers.set()
        for connection in parent_connections:
            connection.close()
        for worker_process in processes:
            worker_process.join(timeout=10)
            if worker_process.is_alive():
                worker_process.terminate()
                worker_process.join(timeout=5)

    node_ids = [node_id for node_id, _generated_ids in results]
    generated_ids = [
        public_id for _node_id, worker_ids in results for public_id in worker_ids
    ]

    assert len(set(node_ids)) == WORKER_COUNT
    assert len(set(generated_ids)) == WORKER_COUNT * IDS_PER_WORKER
    assert all(
        ((public_id >> SNOWFLAKE_NODE_ID_SHIFT) & SNOWFLAKE_MAX_NODE_ID) == node_id
        for node_id, worker_ids in results
        for public_id in worker_ids
    )
    assert all(process.exitcode == 0 for process in processes)
